apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hermes-agent.configMapName" . }}
  labels:
    {{- include "hermes-agent.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- if .Values.config.raw }}
    {{- tpl .Values.config.raw . | nindent 4 }}
    {{- else }}
    {{- tpl (toYaml .Values.config.values) . | nindent 4 }}
    {{- end }}
  {{- if .Values.soul.text }}
  SOUL.md: |
    {{- tpl .Values.soul.text . | nindent 4 }}
  {{- end }}

