{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hermes-agent.secretName" . }}
  labels:
    {{- include "hermes-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{- if and (ne $key "existingSecret") (ne (printf "%v" $value) "") }}
  {{ $key }}: {{ tpl (printf "%v" $value) $ | quote }}
  {{- end }}
  {{- end }}
{{- end }}

